apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: MjI2NDQyMV9sYWVlcQ==
  database-root-password: MjI2NDQyMV9yb290
  database-user: bGFlZXE=
kind: Secret
metadata:
  annotations:
  labels:
    app: dpaas-mariadb
  name: dpaas-mariadb
  namespace: serving
type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dpaas-mariadb-pv
  labels:
    storage: dpaas-mariadb-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.0.8
    path: "/data/kube-pv/manual/dpaas/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  dpaas-mariadb-pvc
  namespace: serving
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # You need to specify this or else it tries default storageclass
  storageClassName: ''
  # Bind to the specific pv above
  selector:
    matchLabels:
      storage: dpaas-mariadb-pv
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: dpaas-mariadb
  name: dpaas-mariadb
  namespace: serving
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dpaas-mariadb
  template:
    metadata:
      labels:
        app: dpaas-mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: dpaas-mariadb
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: dpaas-mariadb
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: dpaas-mariadb
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: dpaas-mariadb
        image: laeeq/ligandprofiledb:0.0.4
        imagePullPolicy: Always
        name: dpaas-mariadb
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mariadb-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: dpaas-mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dpaas-mariadb
  namespace: serving
  labels:
    app: dpaas-mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: dpaas-mariadb
  clusterIP: None
