---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: dpaas-receptor1
  name: dpaas-receptor1
  namespace: serving
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dpaas-receptor1
  template:
    metadata:
      labels:
        app: dpaas-receptor1
    spec:
      containers:
      - env:
        - name: MARIADB_IP
          value: "dpaas-mariadb.serving.svc.cluster.local"
        - name: MARIADB_PASSWORD
          value: mariadb_root
        - name: CORS_URL
          value: "https://ptpaas-dpass.k8s-prod.pharmb.io"
        - name: RECEPTOR_NAME
          value: 'HIV_RT'
        - name: RECEPTOR_PDBCODE
          value: '1E66'
        name: receptor1
        image: laeeq/cpvsapi:1B8O-0.0.1 #laeeq/cpvsapi:1RT2-0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: 1536Mi
          requests:
            memory: 256Mi
        securityContext:
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: dpaas-receptor1
  labels:
    app: dpaas-receptor1
  namespace: serving
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: dpaas-receptor1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
    app: dpaas-receptor1
  name: dpaas-receptor1
  namespace: serving
spec:
  rules:
  - host: receptor1-dpass.k8s-prod.pharmb.io
    http:
      paths:
      - backend:
          serviceName: dpaas-receptor1
          servicePort: 80
        path: /
  tls:
    - secretName: dpaas-receptor1-ingress-tls
      hosts:
        - receptor1-dpass.k8s-prod.pharmb.io
